spring:
  application:
    name: 11-cqrs
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cqrs-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.scaleatdesign.*
  datasource:
    url: jdbc:postgresql://localhost:5432/ipce
    username: ipce
    password: ipce
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: cqrs
    show-sql: false

server:
  port: 8101
